name: CarePackage
main: com.caved_in.lootkrate.LootKrate
version: 0.1
description: Randomly Spawning CarePackages!
author: CrowdedAttorney
softdepend: [Commons]
commands:
   cp:
      description: Main command for the CarePackage plugin
      usage: /<command>
